---
title: "facet_ggplot2"
author: "Gabriel Sartori"
date: ""
output: html_document
editor_options: 
  chunk_output_type: console
---

---
## Mercado Imobiliário 

+ Curitiba
+ Valor Locação 
+ Apartamento
+ Quartos: 1 e 2


```{r, echo = FALSE}
moradia_quarto2_1 <-
  loca_tipologia_quarto %>% 
  filter(quarto == 2 | quarto == 1) %>% 
  ungroup() %>% 
  spread(tipologia, media_locacao) %>% 
  na.omit() %>% 
  mutate(bairro = toupper(bairro)) %>% 
  inner_join(cwb, by = "bairro") %>% 
  mutate(quarto = paste("Quarto: ", quarto))

```

```{r, echo = FALSE}
moradia_quarto2_1  %>% 
  st_as_sf() %>% 
  select(bairro, quarto, apartamento)
```

---

```{r facetmapa, eval = F, echo = F, comment = "", warning = FALSE}
ggplot() +
  geom_sf(data = cwb, fill = "gray80", colour = "white") +
  geom_sf(data = moradia_quarto2_1, aes(fill = apartamento))  +
  facet_wrap(~quarto, ncol = 2) +
  scale_fill_gradientn(colours = brewer.pal(5, "Oranges"), na.value = "white", labels = number_br) +
  labs(fill = "Valor")  +
  theme_void() +
  theme(legend.key.size =  unit(0.5, "cm")) + 
  theme(panel.grid.major =  element_line(colour = "transparent"))
```

`r paste(knitr::knit(text = partial_knit_chunks("facetmapa")), collapse = "\n")`
---